apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ci-cd-app-monitor
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: ci-cd-app
  endpoints:
    - port: http
      path: /metrics
      interval: 15s