apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name}}
  namespace: {{ .Values.namespace }}
  labels:
    app: ci-cd-app
spec:
  type: {{ .Values.service.type }}
  selector:
    app: ci-cd-app
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 5000